version: '3.8'
services:
  db:
    restart: always
    container_name: postgres
    image: postgres:16.1-alpine
    command: -N 1000
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgrespass}
      POSTGRES_DB: ${DB_NAME:-newsletter}
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
