version: '3.8'
services:
  api:
    restart: always
    container_name: z2p-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      APP_ENVIRONMENT: ${APP_ENVIRONMENT:-production}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health_check"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    restart: always
    container_name: z2p-postgres
    image: postgres:16.1-alpine
    command: -N 1000
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgrespass}
      POSTGRES_DB: ${DB_NAME:-newsletter}
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
