application:
  port: 8000
database:
  host: localhost
  port: 5432
  username: postgres
  password: postgrespass
  name: newsletter
email_client:
  base_url: http://localhost
  sender_email: test@example.com
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
