application:
  port: 8000
  host: 0.0.0.0
database:
  host: localhost
  port: 5432
  username: postgres
  password: postgrespass
  name: newsletter
  require_ssl: false
email_client:
  base_url: localhost
  sender_email: test@example.com
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
